### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by ghost** [ObelusFamily/Anythink-Market-bg6y9iu9#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by denoku** [comment]
![image](https://user-images.githubusercontent.com/108004386/207183506-2e36a3a1-0c34-4222-bb9f-2474b5a3030a.png)
